---

- hosts: webservers
  name: Gether facts from webservers
  user: root
  tasks:
    - fail: msg=""
      when: false

- name: Setup Appservers
  hosts: appservers
  user: root

  roles:
    - ufw_app
    - nginx
