---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration files
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: delete default vhost
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
