---

- name: Allow http from webservers
  ufw: rule=allow port={{item[1]}} src={{hostvars[item[0]]['ansible_eth1']['ipv4']['address']}}
  with_nested:
    - groups['webservers']
    - [80, 8000] #delete 80 when not depending on web_00
